export const MUNICIPIOS_CHOCO = [
  "Acandí",
  "Alto Baudó",
  "Atrato",
  "Bagadó",
  "Bahía Solano",
  "Bajo Baudó",
  "Bojayá",
  "Carmen del Darién",
  "Cértegui",
  "Condoto",
  "El Cantón del San Pablo",
  "El Litoral del San Juan",
  "Istmina",
  "Juradó",
  "Lloró",
  "Medio Atrato",
  "Medio Baudó",
  "Medio San Juan",
  "Novita",
  "Nuquí",
  "Quibdó",
  "Río Iro",
  "Río Quito",
  "Riosucio",
  "San José del Palmar",
  "Sipí",
  "Tadó",
  "Unguía",
  "Unión Panamericana",
];